### ISSUE TITLE
Email Validation Error

### ISSUE THREAD

**Issue by dink** [JasonBaier/ci3-fire-starter#28] opened 2016-09-06 20:56 UTC
Every instance of a form throws up a error

`The Email field must contain a valid email address.`

and it comes down to this validation rule: `valid_email`

Anyone else having this problem?

**Comment by JasonBaier** [comment] 2016-12-14 16:08
Are you referring to the Contact form? I can not replicate this issue when entering a valid email address.

**Comment by JasonBaier** [comment] 2017-01-09 17:52
Since I can not replicate, I am closing this issue. Please reopen if you can provide more specific information on how to reproduce.

**Closed as completed by JasonBaier** 2017-01-09 17:52 UTC
